{
    "name": "Estate Account",
    "version": "1.0",
    "sequence": 2,
    "category": "Real Estate",
    "summary": "Estate Account",
    "description": "",
    "website": "https://google.com",
    "depends": ["estate", "account"],
    "data": [],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
}
